// Code generated by "stringer -type=SolverType"; DO NOT EDIT.

package maze

import "strconv"

const _SolverType_name = "GrowingTreeNewestGrowingTreeRandomGrowingTree50Split"

var _SolverType_index = [...]uint8{0, 17, 34, 52}

func (i SolverType) String() string {
	i -= 1
	if i < 0 || i >= SolverType(len(_SolverType_index)-1) {
		return "SolverType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SolverType_name[_SolverType_index[i]:_SolverType_index[i+1]]
}
